language: node_js
node_js:
- node
cache:
  directories:
  - "$HOME/.npm"
script:
- npm run generate
deploy:
  provider: s3
  access_key_id: AKIAID2C4IR76MAET67Q
  secret_access_key:
    secure: jhZbq3cM3RuHmv8dZJmWgO0H5CUxXhDTJGn6ON0GydGuBRHSylTHJRWgYMPHM4TMcQ0qsv7UVLS/kk901gAg9nZmv6RFZGeakJ0CFAUYMVw4XXGRd1v0vK5OZfrQvurD3NtJDHdRrbGInRzFGGGEfv1+9J0ye1XmHDiIlCYr4vAcKEBUhYOX0n0brGqUJylH0J3IOGFIXQ/aKMLy+7t9Ra7M70J4oOzbsjqpn6DBQ8oKBCm6bDBugntTc4JkOJIkPGM6iSL6h3W2EQuFWKTF0NzhQ/f2aKj5KLGC+STMmd935EoaWe5fTvS4GLMZ1xXwr6coqMEKpfU7zPvzUFDbe5LiRvhJLgz2HN9tT868f+s/7Usvcx76v/7WTrzBjl+1CXEAwDZ/eODvIFhnuAuXZXmO2EGZJvLD6p/Gs2bwQtkqtqsVSY/nQ0Cst2824jDgyZYbyvz/erCkDGgLN5+l7i4VX4/IxUAoUEraYnMVHRVJlihi3MYFY8eHqt7V8GVtZJCKucZdMZyytLGgtIAgvZsOJVWmKji1TttuAc1MrGgWr56mMsaJUBbtkn8JmUFn5Cqai0FLeUp80TQBhTqGPTesjM6I1j7XGQ00Xvbxw0aN7SSmeJyRfNcZ12pxqHjnVGrqdzhAeKxNX147zAq2eDDmjZkUEkJr0G5zoVh4Htc=
  bucket: aidan.rocks
  local-dir: dist
  acl: public_read
  skip_cleanup: true
  region: ca-central-1
branches:
  only:
  - master
