language: node_js
node_js:
- node
cache:
  directories:
  - "$HOME/.npm"
script:
- npm run generate
deploy:
  provider: s3
  access_key_id: AKIAID2C4IR76MAET67Q
  secret_access_key:
    secure: s3lNeXmNssEW8PfvzdvTT8H9xJfQIWccu3I2nReWqj3IfUXLF2cTWprdOcd0EqIJvC4GADORucFMF5dTvloYqaNh1tdDQ/MngAdiqGNHlJg1oku4BBeJgcFXEsQ3B7TtiK55lcCD+ive2TRHbbKi5sbK6rivXw1IJsPAZWbM2UqPvjP26FhlLat+aqgcndYD62le0PMaT/u11z7D3DIcCixE/57Fhp2ASdKCw2QyiPEA4sYmYx/peLt+gZA5+p34BCaDxjPGn4XGqtxciiA4or9P3UJRSkJLBYS7grxAw/wmAo96xCdzmczmfKzBYalELcxVTFK5Ffr8fYyvNob3Q/BouJp8s+FIHfws/5Z/YcLK5m0iG5aTBBA3wTUbhO2IbLHhfKyihKu8XzWvu7+6mytPaN0n3WrWkqNN5pvoKf7YUlS21yyR0AGqUpjsv27oPHvJ837Rneuo2nmGpCY77lNLH0GQuciOSw8hDwkrnXWJztjzu7CAAIxLYEhP5I7n25uqegSHEvZyY3+6kA0KHDdJihZVDjPdRkIuDMzIBOcUa689LRIyHYhrHSeYjlRmueeN5O9xQM/5TtVSXgZdnsCqped7NTmDeBKHu3ZJgu8B174oH26owC1tORS4656Ih6+FO7RLVATd6qsh2cevY21714tLE7FXXwdq1Gxt8CM=
  bucket: aidan.rocks
  local-dir: dist
  acl: public_read
  on:
    repo: aoldershaw/aidan.rocks
branches:
  only:
  - master
