language: node_js
node_js:
- node
cache:
  directories:
  - "$HOME/.npm"
script:
- npm run generate
deploy:
  provider: s3
  access_key_id: AKIAIWHYISVC2CQZPOQA
  secret_access_key:
    secure: CWA9xAik3Ms3nHbHst6o+Voi8qQinpEczVTY5oKGmjSqDxtSwESTOtpbvHKfHD8XBNShcbu2UZY3+cZH+Y7RL6cSTP6bRnYZ9u5lqoFlM0IPCd4L8CX7dNKn2xmhOFSz2pU3byGilVEaGCWzdJw5RRonqh9VFWYsD5ZOYH18jJYM0WXO7+2sGCNggYl4OEtlzHK76dr8qUlaVLd+fM5iGcL0IrJliR/1+/w16BQdhSL50lmnlfvkp7QuQGUtXUgRT3H+wyJG8Q2bWcdgqz+K/ZFFq0ZdR9463ZO8ooMM3JvbiaTr54EBsMxIpdG/nVhmcZlcN4FhavYGlPNhT1ohAaVRGxgUf8lDZO+NuI1K0t7i//gOHrWgmmzode6mPCH6LXqdo0STHFWTffa4PEUyWvHLxFsRQ+Bmez+mQZ7nr4gJlAj06XyDblwyLepel3FlLDt1jinqvcOAQcDopWpuPUjATg0wlNHc+tUg6gR/CmEPpqf/WMsZ3GLNVFBoAKWfCmdonkbKtuRjj+wQMs1AVUBQysDWjtY5U2Aidak55PurqE5bvNq2X6ZwnRxKxLj563Zh2erwjizm9ihTjC3xQWglQyTbtN31Ymsd7gih96We0SV5fwxcmEmWsWtPP2+uIX/vSsKbxOxNV6mOMReZSBSNrUuz8CM5IZT3B8Rhgyk=
  bucket: aidan.rocks
  local-dir: dist
  acl: public_read
  on:
    repo: aoldershaw/aidan.rocks
  skip_cleanup: true
branches:
  only:
  - master
